# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_auto_20170614_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocatedresources',
            old_name='resource_description',
            new_name='allocation_description',
        ),
    ]
