# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0004_auto_20170809_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetypes',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=8),
        ),
    ]
